version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: '%(asctime)s - %(filename)s - %(lineno)d - [%(levelname)s] %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout
  logfile:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: simple
    filename: common/inf.log
    maxBytes: 10485760
    backupCount: 3
loggers:
  service:
    level: DEBUG
    handlers: [logfile]
    propagate: 0
root:
  level: ERROR
  handlers: [console, logfile]